language: node_js
node_js:
- '6'
env:
  global:
  - secure: hFvo2Dv08a3vx/91c/Xc/T4bZb7ibOJlNpwRJz4A6DnUoyhdklPaDDhv4R7W1mFWiTM1JxGIGV/st3amGkOzDZMEYHSFMRsQk/FLEryquDYYZhvadjFZbzsaL6lNYZB5KShY4TAzHBh3cBLhR7q30UvOD8WZHi3X8VcbPqm8kMrfVMuqp13BaIikFqFl2yD1RcKTfSXclYnvcoEznRNo6c0A5/S48TvXYMgfE0vTulDcab0NkT/5WzyIimMb0mOMGWtP0DV0F/NUjypXJeBLD9SoA+W1pQoS2XTof3CZ5doGOR6tTDoo6PLwkrEo9bG9yD0oupepmSJzpjmZYKai6RBsFW3e/tKltx8PpqxKItuFOBXkcO8yIkT0NpF05JldF8FhL/cOK62VYs/buS4I0mp43zqSsDgHXoBkaXLupCWld62HVpoQa++RKwqO/DRrhQLzawXbeZrw5ISDq6t9scWbF+AJ/C5d/regtd5RATLbSlj4ACergN1MEzsZVurfsnZeqchzFIsDZQSBZOOmuG820WVUm+n60C9uCly8qAPHKHjdhtnZIa3BJLmVTfWKKdNQS+AWR3d5DFrF3y3Ix50uOMYJesbpUfXhgdFlMSpPTWMnNGH+bPu7U8OQMq1y3Nd0J6oPOIGg6OJn8kMmk9xufYCH/t7MrEzSvWbqPFY=
before_install:
- openssl aes-256-cbc -K $encrypted_ed0cdc322443_key -iv $encrypted_ed0cdc322443_iv
  -in .deployscp.enc -out .deployscp -d
deploy:
  provider: script
  skip_cleanup: true
  script: npm deploy
  on:
    branch: master