sudo: required
services:
  - docker

language: node_js
node_js:
- '6'

before_deploy:
- npm run package
deploy:
  skip_cleanup: true
  script: docker build .
  on:
    branch: master
  
before_install:
- openssl aes-256-cbc -K $encrypted_ed0cdc322443_key -iv $encrypted_ed0cdc322443_iv
  -in .env.enc -out .env -d
