sudo: required

services:
  - docker

language: node_js
node_js:
- '6'

before_install:
  - docker build -t sigsegv/pizzabot:$TRAVIS_COMMIT .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push sigsegv/pizzabot:$TRAVIS_COMMIT;

after_success:
  - curl -k -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
  - chmod +x sloppy
  - if [ "$TRAVIS_BRANCH" == "master" ];then ./sloppy change -v docker_image:"sigsegv/pizzabot:$TRAVIS_COMMIT" .sloppy.yml; fi

