version: 0.1

phases:
  install:
    commands:
      - echo Installing ...
      - chmod +x ./build/*.sh
      - ./build/install.sh
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - aws s3 cp $ENV_FILE .env
      - npm run package
artifacts:
  files:
    - target/slackbot.tar.gz
  discard-paths: yes